import Sidebar from '@/components/Sidebar'

import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import SupabaseProvider from '@/providers/SupabaseProvider'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Music Streaming',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SupabaseProvider>
        <Sidebar>
          {children}
        </Sidebar>
      </SupabaseProvider>
    </html>
  )
}
